export const LAY_DATA = "GET_DATA";
export const LAY_CHI_TIET_PHIM = "GET_DETAIL_MOVIE"
export const LAY_DATA_RAP = "GET_DATA_RAP";
export const LAY_CHI_TIET_RAP = "GET_DETAIL_RAP"
export const LAY_LICH_CHIEU_RAP = "GET_DATA_LICHCHIEU_RAP"
